"use client";
import React, { useEffect, useRef } from "react";

export default function AutoGeneratedReports() {
  const contentRef = useRef(null);

  useEffect(() => {
    const elements = contentRef.current?.querySelectorAll(".fadeUp");
    if (!elements) return;

    Array.from(elements).forEach((element, index) => {
      element.style.opacity = "0";
      element.style.transform = "translateY(40px)";
      element.style.transition = "opacity 0.8s ease, transform 0.8s ease";

      setTimeout(() => {
        element.style.opacity = "1";
        element.style.transform = "translateY(0)";
      }, 100 + index * 100);
    });
  }, []);

  const reports = [
    {
      title: "Weekly Compliance Report",
      date: "Dec 1-7, 2024",
      type: "Hand Hygiene",
      status: "ready",
      compliance: 86,
      insights: "3% improvement from last week",
      icon: "📊",
    },
    {
      title: "Monthly Department Analysis",
      date: "November 2024",
      type: "All Departments",
      status: "ready",
      compliance: 84,
      insights: "ICU shows highest compliance",
      icon: "🏥",
    },
    {
      title: "Quarterly Trend Report",
      date: "Q4 2024",
      type: "Infection Control",
      status: "processing",
      compliance: null,
      insights: "Expected completion: Dec 15",
      icon: "📈",
    },
    {
      title: "Annual Performance Summary",
      date: "2024",
      type: "Full Hospital",
      status: "scheduled",
      compliance: null,
      insights: "Scheduled for Jan 5, 2025",
      icon: "📅",
    },
  ];

  const chartData = [
    { month: "Jul", compliance: 78 },
    { month: "Aug", compliance: 81 },
    { month: "Sep", compliance: 79 },
    { month: "Oct", compliance: 83 },
    { month: "Nov", compliance: 84 },
    { month: "Dec", compliance: 86 },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-900 via-teal-900 to-green-900 relative overflow-hidden">
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute top-20 left-10 w-72 h-72 bg-teal-500 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-pulse"></div>
        <div className="absolute top-40 right-10 w-96 h-96 bg-blue-500 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-pulse delay-75"></div>
        <div className="absolute bottom-20 left-1/3 w-80 h-80 bg-green-500 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-pulse delay-150"></div>
      </div>

      <div className="relative z-10 px-4 py-16" ref={contentRef}>
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12 fadeUp">
            <div className="mb-6 inline-block">
              <div className="w-24 h-24 bg-gradient-to-br from-teal-400 to-green-500 rounded-2xl flex items-center justify-center shadow-2xl transform hover:scale-110 transition-transform duration-300 mx-auto">
                <span className="text-5xl">📈</span>
              </div>
            </div>
            <h1 className="text-5xl md:text-6xl font-bold text-white mb-4 tracking-tight">
              Auto-Generated{" "}
              <span className="bg-gradient-to-r from-teal-400 via-green-400 to-blue-400 bg-clip-text text-transparent">
                Reports
              </span>
            </h1>
            <p className="text-xl text-white opacity-90">
              Instant insights at your fingertips
            </p>
          </div>

          <div className="fadeUp mb-12">
            <div className="bg-[#2B624E] bg-opacity-20 backdrop-blur-lg rounded-3xl p-8 border border-white border-opacity-20">
              <h2 className="text-2xl font-bold text-white mb-6 flex items-center gap-3">
                <span className="text-3xl">📊</span>
                6-Month Compliance Trend
              </h2>
              <div className="relative h-64">
                <div className="absolute inset-0 flex items-end justify-around gap-4">
                  {chartData.map((data, index) => (
                    <div
                      key={index}
                      className="flex-1 flex flex-col items-center gap-2"
                    >
                      <div
                        className="w-full bg-white bg-opacity-10 rounded-t-lg relative"
                        style={{ height: `${data.compliance}%` }}
                      >
                        <div
                          className="absolute inset-0 bg-gradient-to-t from-teal-400 to-green-400 rounded-t-lg"
                          style={{ height: "100%" }}
                        ></div>
                        <div className="absolute -top-8 left-1/2 transform -translate-x-1/2 text-white font-bold text-sm">
                          {data.compliance}%
                        </div>
                      </div>
                      <span className="text-white text-sm font-semibold">
                        {data.month}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
              <div className="mt-8 flex items-center justify-center gap-2 text-green-400">
                <span className="text-2xl">↑</span>
                <span className="font-semibold">
                  +8% improvement over 6 months
                </span>
              </div>
            </div>
          </div>

          <div className="fadeUp mb-12">
            <h2 className="text-3xl font-bold text-white mb-6">
              Available Reports
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {reports.map((report, index) => (
                <div
                  key={index}
                  className="bg-[#2B624E] bg-opacity-20 backdrop-blur-lg rounded-2xl p-6 border border-white border-opacity-20 hover:bg-opacity-25 transition-all"
                >
                  <div className="flex items-start justify-between mb-4">
                    <div className="flex items-center gap-3">
                      <div className="text-4xl">{report.icon}</div>
                      <div>
                        <h3 className="text-xl font-bold text-white">
                          {report.title}
                        </h3>
                        <p className="text-sm text-white opacity-70">
                          {report.date}
                        </p>
                      </div>
                    </div>
                    {report.status === "ready" && (
                      <span className="px-3 py-1 bg-green-500 bg-opacity-20 text-green-400 text-xs rounded-full border border-green-400 border-opacity-30 font-semibold">
                        Ready
                      </span>
                    )}
                    {report.status === "processing" && (
                      <span className="px-3 py-1 bg-yellow-500 bg-opacity-20 text-yellow-400 text-xs rounded-full border border-yellow-400 border-opacity-30 font-semibold">
                        Processing
                      </span>
                    )}
                    {report.status === "scheduled" && (
                      <span className="px-3 py-1 bg-blue-500 bg-opacity-20 text-blue-400 text-xs rounded-full border border-blue-400 border-opacity-30 font-semibold">
                        Scheduled
                      </span>
                    )}
                  </div>

                  <div className="space-y-2 mb-4">
                    <div className="flex items-center justify-between">
                      <span className="text-white opacity-70 text-sm">
                        Type:
                      </span>
                      <span className="text-white font-semibold text-sm">
                        {report.type}
                      </span>
                    </div>
                    {report.compliance !== null && (
                      <div className="flex items-center justify-between">
                        <span className="text-white opacity-70 text-sm">
                          Compliance:
                        </span>
                        <span
                          className={`font-bold text-sm ${
                            report.compliance >= 85
                              ? "text-green-400"
                              : report.compliance >= 75
                              ? "text-yellow-400"
                              : "text-red-400"
                          }`}
                        >
                          {report.compliance}%
                        </span>
                      </div>
                    )}
                    <div className="flex items-center gap-2">
                      <span className="text-white opacity-70 text-sm">💡</span>
                      <span className="text-white text-sm">
                        {report.insights}
                      </span>
                    </div>
                  </div>

                  {report.status === "ready" && (
                    <div className="flex gap-2">
                      <button className="flex-1 bg-white bg-opacity-10 backdrop-blur-sm text-white px-4 py-2 rounded-lg font-semibold text-sm hover:bg-opacity-20 transition-all">
                        View Report
                      </button>
                      <button className="flex-1 bg-gradient-to-r from-teal-500 to-green-500 text-white px-4 py-2 rounded-lg font-semibold text-sm hover:from-teal-600 hover:to-green-600 transition-all">
                        Download PDF
                      </button>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

          <div className="fadeUp">
            <div className="bg-gradient-to-r from-teal-500 to-green-500 rounded-3xl p-8 shadow-2xl">
              <h2 className="text-3xl font-bold text-white mb-6 text-center">
                Key Insights from Latest Reports
              </h2>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="bg-white bg-opacity-10 backdrop-blur-sm rounded-2xl p-6 text-center">
                  <div className="text-4xl mb-3">🏆</div>
                  <div className="text-3xl font-bold text-white mb-2">92%</div>
                  <p className="text-white text-sm">
                    Top Performing Department (ICU)
                  </p>
                </div>
                <div className="bg-white bg-opacity-10 backdrop-blur-sm rounded-2xl p-6 text-center">
                  <div className="text-4xl mb-3">📈</div>
                  <div className="text-3xl font-bold text-white mb-2">+8%</div>
                  <p className="text-white text-sm">
                    Overall Improvement (6 months)
                  </p>
                </div>
                <div className="bg-white bg-opacity-10 backdrop-blur-sm rounded-2xl p-6 text-center">
                  <div className="text-4xl mb-3">⏱️</div>
                  <div className="text-3xl font-bold text-white mb-2">
                    2 min
                  </div>
                  <p className="text-white text-sm">
                    Average Report Generation Time
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="absolute bottom-0 left-0 right-0 h-1 bg-gradient-to-r from-teal-400 via-green-400 to-blue-400"></div>
    </div>
  );
}
