"use client";
import React, { useState, useEffect } from "react";
import { useSearchParams } from "next/navigation";
import StaffComplianceDashboard from "./staffCompliance";
import ElectronicAuditForm from "./electronicAudit";
import AutoGeneratedReports from "./autoReports";
import LowPerformanceAlerts from "./lowPerform";

export default function ChallengePage() {
  const searchParams = useSearchParams();
  const [activeTab, setActiveTab] = useState("staff");

  useEffect(() => {
    const tabFromUrl = searchParams.get("tab");
    if (
      tabFromUrl &&
      ["staff", "audit", "reports", "alerts"].includes(tabFromUrl)
    ) {
      setActiveTab(tabFromUrl);
    }
  }, [searchParams]);

  const renderContent = () => {
    switch (activeTab) {
      case "staff":
        return <StaffComplianceDashboard />;
      case "audit":
        return <ElectronicAuditForm />;
      case "reports":
        return <AutoGeneratedReports />;
      case "alerts":
        return <LowPerformanceAlerts />;
      default:
        return <StaffComplianceDashboard />;
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-900 via-teal-900 to-green-900">
      <div className="transition-all duration-300">{renderContent()}</div>
    </div>
  );
}
